### ISSUE TITLE
One treacherous line of code

### ISSUE THREAD

**Issue by nikita-moor** [Flashwalker/hzclish#1]
All 3 examples from the help do not work without `-P` parameter:

https://github.com/Flashwalker/hzclish/blob/ed793359003143961024206074ca8fab1e03e2f1/hzclish#L79-L82

(exclamation mark "!" should be escaped in Bash "\\!".)

Output:

```
[error] no content
Error or invalid token, requesting new one...
```

The problem goes from the next line:

https://github.com/Flashwalker/hzclish/blob/ed793359003143961024206074ca8fab1e03e2f1/hzclish#L612

which is

```sh
if (($bb)) || (($html)); then
    cat "$msgbody";
else
    cat "$msgbody" | $markdown;
fi
```

Because neither `$bb` nor `$html` are set by default routine goes to the "else" branch, but `$markdown` is empty as pandoc's part is already bypassed (line [#594](https://github.com/Flashwalker/hzclish/blob/ed793359003143961024206074ca8fab1e03e2f1/hzclish#L594)).

The same line prevents using Pandoc:

https://github.com/Flashwalker/hzclish/blob/ed793359003143961024206074ca8fab1e03e2f1/hzclish#L802-L805

As `$html` is set True, the above mentioned line #612 does not actually translate md > bb.

**Comment by Flashwalker** [comment]
Hi. Thanks for report, nice catch. I will fix it as soon as find time. Or you can send pull request

**Comment by Flashwalker** [comment]
> All 3 examples from the help do not work without `-P` parameter:...

I fixed it.

And it looks like it was about [this](https://unix.stackexchange.com/questions/87457/overwriting-an-input-file) issue too. Probably bash version relative issue.
